# Use an official Python runtime as a base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /project_docker/

# Copy the Python script and CSV file to the working directory
COPY read_data.py .
COPY Bank_Deposite.csv .
COPY preprocessing.py  .
COPY Bank_Deposite_Model.csv .
COPY Model_Selection.py .
COPY Logistic_acc.txt . 
COPY KNN_acc.txt .
COPY Decision_Tree_acc.txt .
COPY Random_Forest_acc.txt .
COPY Linear_SVM_acc.txt .
COPY XGBoost_acc.txt .
# Install necessary packages for the application
RUN apt-get update && apt-get install -y nano

# Install Python dependencies
RUN pip install pandas numpy seaborn matplotlib scikit-learn scipy

# Clean up package caches and unnecessary files
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


# Define the command to run your application
CMD ["python", "read_data.py" , "Preprocessing.py","Model_Selection.py"]

EXPOSE 80 